### PR TITLE
Change the way RA rules are applied

### PR DESCRIPTION
**Pull request by Frodfurgurn1991**
So, right now, for each slave, the RA loops through all the rules that apply to her and makes the changes specified.  This has several consequences.  First of all, if more than one rules act on some "attribute", like say the clothes, you'll get messages like "x is now wearing this. x is now wearing that".  Secondly, it's kinda inefficient.  This doesn't matter that much because you generally have a small number of rules, but still.

What is PR does instead is that it merges all the applying rules into one, and then acts according to that.  So no more silly doubled messages and no more "last...Rule" functions!

Not everything is merged though.  In particular, jobs and facility assignments are still done the "old way", inside a loop.  So you may still see doubled messages for that.

In general though, this results both in simpler code and better messages.

This is not the only change this PR makes though.  It also eliminates rule variables that were never used and combines some other ones.

### CODE REVIEW

**Comment by Frodfurgurn1991** [comment]
This will conflict with #398, since they both change initRules.tw etc.  That PR is meant to be pulled first.  After that, I'll fix the conflict if you want.

**Comment by fcpmanon** [comment]
The .choosesOwnClothes variable tracks whether the slave should change her clothes again in later weeks, since once she chooses an outfit for the current week her clothes variable will be set to a specific outfit.

**Comment by Frodfurgurn1991** [comment]
That may be the case for the slave itself.  However, when talking about rules, the .clothes variable of a rule will never change through the week.

**Comment by fcpmanon** [comment]
Ah, I see.  You still set the slave's own chooses variable in raWidgets.  Thanks for clarifying.

**Comment by freecitiesdev** [comment]
> That PR is meant to be pulled first. After that, I'll fix the conflict if you want.

Fire at will.

**Comment by Frodfurgurn1991** [comment]
Looks ok now.

**Comment by Frodfurgurn1991** [comment]
fuck, I messed that up

**Comment by freecitiesdev** [comment]
Reposting from #398 because this is the only other PR which has changed the RA. Pretty sure it's that one, but in any case:

**Comment by freecitiesdev** [comment]
Reverting this PR for now. At minimum, it breaks exclusions, applying rules to slaves in facilities regardless of facility exclusion settings, producing all kinds of issues. See #429.

**Comment by Frodfurgurn1991** [comment]
Moving the #398 discussion here since this is the relevant PR.

So, any luck with that fix?

**Comment by Frodfurgurn1991** [comment]
@freecitiesdev ping

**Pull request merged**
