### PR TITLE
Cherrypick of commits since #187

### PR DESCRIPTION
**Pull request by freecitiesdev**
Attempted partial resolution of a versioning issue I seem to have introduced with #193. Reapplies commits since #186-#185. Only known lost changes at this point are the javascript operators changed in #187 that directly conflict with subsequent changes. Apologies to Folant and anyone else inconvenienced; I'm about 90% sure I know where I went wrong and how to avoid doing so in the future.

If someone with more GitHub knowledge can easily see a more elegant resolution to this, jump in.

### CODE REVIEW

**Comment by Bane70** [comment]
Ah I was wondering what happened. I seem to be not getting notifications of things on here, but they are showing up in my emails. I was unaware you had updated the master and I went and posted a fix that had a major conflict. looks like the facility arrays are totally gone besides maybe #185, from the little I've looked around and saLongTermEffects seems to be partly missing, errors while trying to build. Also the fix I did was something that should not of needed fixing as that was well tested a missing $i = _FLs for the stewardess, but I did have more than one edit of it up so maybe git got confused on the merge of that but shouldn't of have.

**Comment by Folant** [comment]
`git reset --hard HEAD~2` restores last working state of the game ( to #191 ) locally for me, I will now try to figure out how to apply changes introduced after that.

**Comment by Folant** [comment]
The most elegant solution I came to today, is to cherry pick #193 on my local branch, automatically replace all of the conditionals to js ---> it will leave only changes from @freecitiesdev WIP  ---> apply and test it then. Later we can think of how to do it on master, with 'revert' maybe.

**Comment by Folant** [comment]
>Apologies to Folant and anyone else inconvenienced

That's my fault actually, I should have done this after release.

**Pull request merged**
