### PR TITLE
Update policies.tw

### PR DESCRIPTION
**Pull request by DrNoOne0**
Should be a fix to the active Future Society Policies section of Policies not showing up.

### CODE REVIEW

**Comment by DrNoOne0** [comment]
Bug fix doesn't work.  Investigating further.

**Comment by DrNoOne0** [comment]
Should be good to go.  Problem was caused by an incorrect variable name during init.  Fix includes a temporary solution in policies.tw that should stay until mod_BackwardsCompatibility.tw gets updated.

**Comment by freecitiesdev** [comment]
What was the bad variable in init?

**Comment by DrNoOne0** [comment]
The bad variable init was $arcologies[0].FSGenderRadicalistLawBimbo.  I changed to $arcologies[0].FSGenderFundamentalistLawBimbo, since that is what the policies.tw passage was looking for.

**Pull request merged**
