### PR TITLE
Click/display macros deprecation

### PR DESCRIPTION
**Pull request by Folant**
Since  click macro is deprecated in  SugarCube 2.8.0 and display is deprecated in 2.15.0 should we replace them wherever possible? If not, just close this PR.

### CODE REVIEW

**Comment by freecitiesdev** [comment]
Have you tested this?

When the click macro deprecation was first mentioned, I ran into trouble replacing the existing incidences, but I don't recall what the exact issue was. If you've tried this and it works, though, objection withdrawn.

**Comment by Folant** [comment]
Yes. I ran two versions at the same time, and everything seems to work fine without errors. Without this, the code already had 18 instances of the link macro, as shown by  ```git grep '<<link' | wc -l```

**Comment by freecitiesdev** [comment]
Outstanding. Forgive the automatic skepticism. I wish I could add a "have you run this to check for glaringly obvious error messages?" confirm box for pull requests.

**Comment by freecitiesdev** [comment]
It does seem to have broken the keyboard shortcuts, though.

**Comment by Folant** [comment]
Hm. I will take a look now, but they seem to be broken even without it.

**Comment by freecitiesdev** [comment]
Interesting. I was doing (unrelated) playtesting right before pulling that code, and they were working fine for me.

**Comment by Bane70** [comment]
Were any of those clicks referring back to the mouse routines in JavaScript? I had once edited some clicks before and killed the hotkeys.

**Comment by Folant** [comment]
@freecitiesdev It seems storyCaption.tw click --> link really broken shortcuts, damn.

**Comment by Folant** [comment]
@Bane70 yeah, seems so. There are 16 click macros in storyCaption.tw 
And all of them are refered in userlib.js like that, I believe
```Mousetrap.bind("enter", function () {
	$("#story-caption #endWeekButton a.macro-click").trigger("click");
});
Mousetrap.bind("space", function () {
	$("#story-caption #nextButton a.macro-click").trigger("click");
});
Mousetrap.bind("c", function () {
	$("#story-caption #manageArcology a.macro-click").trigger("click");
});```

**Comment by Folant** [comment]
Maybe if I change trigger("click") to trigger("link") it'll work.

**Comment by Bane70** [comment]
Maybe. I'm no JS expert though.

**Comment by Bane70** [comment]
Lol come to think of it that was the same passage I had edited when I killed the hotkeys, that or costs.

**Comment by Folant** [comment]
Fixed in #132

**Pull request merged**
