### PR TITLE
remove unused cosmeticPiercings property

### PR DESCRIPTION
**Pull request by goldifrocks**
hi!

this removes the completely unused cosmeticPiercings property for all slaves.

### CODE REVIEW

**Comment by ObstacleCorpse** [comment]
Thanks. Flagged for FC Dev's review.

**Comment by freecitiesdev** [comment]
Thanks, merged. The stat used to govern nasal, eyebrow, etc. piercings together.

**Comment by goldifrocks** [comment]
I am afraid this got reverted by https://github.com/Free-Cities/Free-Cities/commit/d34ecd9252a8631d8b9e80505c4d2e1a2456699b again :-(

**Comment by ObstacleCorpse** [comment]
Thanks for the notice. I'll reapply the changes manually today.

**Comment by ObstacleCorpse** [comment]
Changes have been re-applied and are in the latest pull request, awaiting FC Dev's approval.

**Comment by goldifrocks** [comment]
no worries, no problem!

**Pull request merged**
