### PR TITLE
Reorganize files

### PR DESCRIPTION
**Pull request by lowercase-donkey**
Created new categories when appropriate.  Time consuming, but hopefully helpful.

### CODE REVIEW

**Comment by lowercase-donkey** [comment]
Looks like it automatically stripped out the empty "uncategorized" folder, apologies.  It's a good folder to keep around.

**Comment by fcpmanon** [comment]
I had a similar idea but was less ambitious in scope and then backed it all out of my pending merge request because it made it harder to see everything else I did

**Comment by lowercase-donkey** [comment]
Sorry for dupes, I think GitHub for windows derped when I switched branches, and then back.  Used [this guide](http://stackoverflow.com/questions/5783159/checking-for-duplicate-file-contents-in-git) and it looks fine now.

**Comment by fcpmanon** [comment]
Perhaps instead of doing this as a pull request, you could make a script with all the move/rename commands in it, and FCDev could run that once and then commit the changes.  It would be much easier to review that way.

**Comment by lowercase-donkey** [comment]
It's bonkers to make though.  Could I get a pull in waves, starting with less common files?  Trying to do this by hand is almost impossible.  The merge would be effortless if could be timed.

**Pull request closed without merging**
