### PR TITLE
UPDATED AND READY TO MERGE:  move $ vars to setupVars; plus some bugfixes and refactoring in separate commits

### PR DESCRIPTION
**Pull request by fcpmanon**
Tested game start, bought some slaves, including shelter slave, ended week a few times, tried one variant of justice event.  Reviewed changes line-by-line in diffs, and did most of the $var to setup-var swaps via regex find-replace, so there shouldn't be too many errors introduced ... if any.

Update:  Tested coursing.  No issues caused by me, but fixed an incidental issue in assign.tw (missing goto $returnTo for assigning pit fighters and lurcher, resulting in a blank screen).  I just reviewed all the diffs again and I don't see any issues.

I think this is safe to merge now.

### CODE REVIEW

**Comment by fcpmanon** [comment]
Tested coursing.  No issues caused by me, but fixed an incidental issue in assign.tw (missing goto $returnTo).

**Comment by fcpmanon** [comment]
I re-based this branch on the latest master commit and reviewed the diffs again.  I unintentionally deleted Boney's changes in saLongTermEffects in my first commit but added them back (with revisions) in my last.  Should be OK to merge now.

**Comment by fcpmanon** [comment]
Added fixes for the remaining issues I noted in #699

**Comment by freecitiesdev** [comment]
Just to be clear, I'm not ignoring this. I'm trying to get another 0.10.3 hotfix out, and I'm saving this for after the last hotfix since it's not a desperately needed fix AFAIK, and is complex.

**Comment by fcpmanon** [comment]
@freectiesdev If you're doing a release, be sure to add the missing <<goto $returnTo>> for Lurcher and Pit in assign.tw - the rest can wait.

**Comment by freecitiesdev** [comment]
Roger that.

**Comment by fcpmanon** [comment]
I've merged in the latest commits including the new slave surname variables (now also moved to setupVars and handled in backwardsCompatibility) and resolved all of the conflicts.  Also added a couple of minor fixes (last two commits).

**Comment by freecitiesdev** [comment]
The next release is at least a week away, so I'm merging this in; I'd appreciate it if you'd monitor it for bugs, since it's such an invasive change.

**Pull request merged**
