### PR TITLE
New Event: Play poker with the mercs

### PR DESCRIPTION
**Pull request by freecitiesbandit**
New event involving a poker night with the mercenaries. There's a few paths and uses the random feature so it doesn't always play out the same way.

### CODE REVIEW

**Comment by Boney-M** [comment]
Losing 1000 rep for not attending their poker night? That seems off, especially when the player could just hit 'continue' and not lose any.

**Comment by freecitiesbandit** [comment]
The rep loss was unintentional, thanks for pointing that out.

IMO, the costs for a lot of the story events are a little too low. If I were to divide the costs in the event by ten, you only get 1000 for a 'big' payout and 100 for a 'safe' payout. At that low a reward, what would the point be? Could still use some tuning though. Maybe 2000-5000 for the big payout?

**Comment by Boney-M** [comment]
5k for the buy-in and thus for the big payout would make it equivalent to the shotgun match, so that would fit well, especially since it's explicitly stated that it's the officers and not the rank-and-file you're playing with.

**Comment by freecitiesbandit** [comment]
I concur and have edited the numbers to reflect that.

**Pull request merged**
