### PR TITLE
code refactoring

### PR DESCRIPTION
**Pull request by Frodfurgurn1991**
Should all be inconsequential changes.

### CODE REVIEW

**Comment by Frodfurgurn1991** [comment]
ruleSlaveSelected and Excluded explicitly check if rule.selectedSlaves is "truthy".  There are several places in raWidgets.tw that also explicitly check if ndef rule.selectedSlaves

I'd really like to eliminate all of those cases...

**Comment by fcpmanon** [comment]
Can you look over my RA changes?  See separate pending merge request.

**Comment by Frodfurgurn1991** [comment]
@fcpmanon What exactly do you want me to check?  Your PR doesn't seem to conflict with mine in anyway.

In any case, I haven't dabbled too much into the RA code just yet... I plan to do a biiig change sometime in the future, if I find the time for it.

**Comment by fcpmanon** [comment]
Your previous comment mentioned changes to the RA widgets.  I made some changes there, so I was hoping you could review since you have ideas about improvements there.

**Comment by Frodfurgurn1991** [comment]
I also have a question pertaining cumAmount... Why is it that slaves with more than 50 or less than -50 health produce the same amount?  While the rest produce less?

**Pull request merged**
