### PR TITLE
Salon focusing on skin

### PR DESCRIPTION
**Pull request by lowercase-donkey**
Feature:
Bodypaint/dye (applied to $activeSlave.skin)

Fixes: 
Allow tan/lighten to appear at same time
Combine skin items into single line

### CODE REVIEW

**Comment by lowercase-donkey** [comment]
Would it be worth defining an $activeSlave.origSkin?  Original skin color was always lost when it was touched by darkening or lightening.  It's going to be even more obvious if my paint changes are acceptable.

**Comment by pregAnon** [comment]
I'd say go for it, if only to have an easy fallback for unsetting paints.

**Comment by freecitiesdev** [comment]
Yeah, I'd support that. Let me know if you want me to do the stat adding and back compat, I've done it enough times that it's nearly automatic.

**Comment by lowercase-donkey** [comment]
@freecitiesdev Better you than me, I haven't tried that yet.  Go for it, if you'd be so kind.

**Pull request merged**
