### PR TITLE
Var fix BackwardsCompatibility.tw

### PR DESCRIPTION
**Pull request by Bane70**
Fixed vars $_Slave. to be _Slave.

Currently working on getting the Fac arrays working.

### CODE REVIEW

**Comment by Bane70** [comment]
I didn't think it went that far back, but I've not gone though everything as of yet. But from what I've seen there's too much new code to revert that far back. An so far my changes have been mostly just replacing the files, but a few need editing and testing, but I'm not that far into it as of yet. Well at least this time I can get the assign widget named right Lol.

**Comment by Folant** [comment]
I think it can be restored. At least I try in #199. I didn't touch your changes to facilities, however

**Comment by Bane70** [comment]
OK. I'm working off a copy that's up to I think it was #188 So anything I do will include up to at least that point.

**Comment by Bane70** [comment]
Yeah that file is missing from the update I'm working from. A I forget about the includes changing. If you want to include my changes in your file I'll close this one so there won't be any conflicts during merge.

**Comment by Folant** [comment]
>I'll close this one so there won't be any conflicts during merge.
There shouldn't be any conflicts, if I'm not wrong

**Comment by Folant** [comment]
https://github.com/Free-Cities/Free-Cities/blob/master/src/uncategorized/mod_BackwardsCompatibility.tw#L1084-L1107
https://github.com/Free-Cities/Free-Cities/blob/master/src/uncategorized/mod_BackwardsCompatibility.tw#L1298-L1376
have the same problems with `$_`

**Pull request merged**
