### PR TITLE
Colorful latex

### PR DESCRIPTION
**Pull request by prndev**
Latex comes in many colours. This update lets you select a outfit color via HTML5 color picker (tested in Firefox and Chrome).

### CODE REVIEW

**Comment by lowercase-donkey** [comment]
Any chance of this coming to shoes?

**Comment by prndev** [comment]
And for shoes! :smiley: (in 30f1d52)

**Comment by lowercase-donkey** [comment]
Ayyyyy!  Not that I need to be color coordinated or anything, but god those blue heels were ugly.

**Comment by prndev** [comment]
I probably should implement an "Arcology fashion colour" selector which overrides the default globally so you don't have to set it for each character individually.

**Comment by lowercase-donkey** [comment]
Seems like a great idea; the RA might be a good place to add it.

**Pull request merged**
