### PR TITLE
Updated Bovine Tattoo descriptions

### PR DESCRIPTION
**Pull request by freecitiesbandit**
@lowercase-donkey I just went ahead and created a new pull request for the changes. Thanks for your previous work and fixing the issues beforehand.

### CODE REVIEW

**Comment by lowercase-donkey** [comment]
With these changes, should we drop the special tat widget I created?  I was trying to preserve the old descriptions, so longSlave calls a widget for cow tats when a slave has cow tats, instead of doing the full dscription.  These are much better though, I feel.

**Comment by freecitiesdev** [comment]
Is it possible to resolve this, or should this be closed?

**Comment by lowercase-donkey** [comment]
It SHOULD be possible, not sure where @freecitiesbandit went.  I'd be happy to copy their work into a new fork, but I don't want to steal their thunder.

**Comment by freecitiesbandit** [comment]
@lowercase-donkey Feel free, given what I did was 100% derivative of your existing work.

**Pull request closed without merging**
