### PR TITLE
Build number replacing

### PR DESCRIPTION
**Pull request by MegaPramuk**
This PR addresses #397.
No batch file modifications because I don't have any Windows machine, so I wouldn't be able to test it.

### CODE REVIEW

**Comment by freecitiesdev** [comment]
Outstanding.

**Comment by Frodfurgurn1991** [comment]
It looks like @freecitiesdev was using that number in a number of places though, to check if the build was recent enough.  Using a commit sha does not allow you to do that unfortunately...

**Comment by MegaPramuk** [comment]
It's not the commit sha1 that's being used.
It's the count of commits.
Only checks that are with `$releaseID` are whether it's bigger or smaller than 1000. So, no checks have been affected.

**Comment by Frodfurgurn1991** [comment]
Sorry, you are right.  That's a great change then!

**Comment by freecitiesdev** [comment]
This doesn't seem to be working at the moment.

**Comment by MegaPramuk** [comment]
Weird, I just tested it out and it works on my machine.

What's the build number for you? Does it say COMMIT?

**Comment by freecitiesdev** [comment]
Well, you can see how I have it now:
`<<set $ver = "0.10.2", $releaseID = COMMIT>>
<<if ndef $releaseID>><<set $releaseID = 1007>><</if>>'
Compiling from a straight download of the repository and firing compile.bat produces FC.html; opening this shows $releaseID as 1007. This is on a Windows box.

**Pull request merged**
