### PR TITLE
Improve weekly reports; fix "choose own assignment" bugs; fix more RA bugs; new feature for Brothel and Club (auto-apply preventatives); suppress some reputation gain text when reputation is capped; several other fixes (including an infinite loop on main)

### PR DESCRIPTION
**Pull request by fcpmanon**

### CODE REVIEW

**Comment by fcpmanon** [comment]
no further bugs encountered yet in playtesting - I think this is ready to merge

**Comment by freecitiesdev** [comment]
>suppress most "society approves ..." text in weekly reports when reputation is capped -- this significantly reduces clutter in the weekly report without loss of content, since you still see everything when it matters: while building reputation

Embarrassed I didn't think of that a long time ago.

**Comment by freecitiesdev** [comment]
Fair warning: I'm about to revert the preventative in facilities stuff in an upcoming PR. Facilities were already modeled as applying preventatives, but badly. I've addressed the issue a different (and more efficient) way.

**Comment by fcpmanon** [comment]
Saw that.  It's a cleaner solution; no need to worry about it.

**Pull request merged**
