### PR TITLE
Degredationist/Paternalist Events

### PR DESCRIPTION
**Pull request by freecitiesbandit**
New REFS Events

### CODE REVIEW

**Comment by lowercase-donkey** [comment]
Always great to see new content, thanks!

**Comment by Boney-M** [comment]
<<if $arcologies[0].FSPaternalist > random(1,100)>>
    <<set $REFSevent.push("paternalist encounter")>>

I'd recommend setting it to something like random(20,100) so that the FS in question needs to be at least somewhat established before the event becomes possible, since the text of the event implies that the FS has achieved some traction in society. The same could be said of the other similar events.

**Comment by WarlordMLP** [comment]
both the confront options have a typo. It says "that does give him impunity to ignore the law"
It should say. "but that doesn't give him impunity to break the law"

**Comment by freecitiesbandit** [comment]
Just saw this. Really sorry for the inconvenience caused. Will try and be more diligent in future.

**Pull request merged**
