### PR TITLE
Minor: Indents in code

### PR DESCRIPTION
**Pull request by lowercase-donkey**
Fixing indents while checking for bugs.

### CODE REVIEW

**Comment by lowercase-donkey** [comment]
Please someone check my work on the merge.

**Comment by Boney-M** [comment]
It seems like the slaveSummary fixes are going to clash pretty hard with #730, which sidestepped some of the indent issues while standardizing full stop placement.

**Comment by Boney-M** [comment]
I didn't mean that it should be deleted, just that it would be something for FC Dev to watch out for while merging - one or the other should be merged first, then the unmerged one might need tweaking to fit with the new version of the file.

**Comment by lowercase-donkey** [comment]
I'm honestly uncomfortable the merge on saLongTerm.  If he takes a look at it that would be great.

**Comment by Boney-M** [comment]
#730 is merged and there's no conflicts, I'm glad my concerns were overstated.

**Pull request merged**
