### PR TITLE
Update BackwardsCompatibility

### PR DESCRIPTION
**Pull request by corncobman**
Multiply oldTrust and oldDevotion for backwards compatibility.

### CODE REVIEW

**Comment by prndev** [comment]
I am in no position to demand anything here, but you might want to do an interactive rebase to squash all previous commits so they do not clutter the history.

**Comment by corncobman** [comment]
I have no idea how to do that.

**Comment by kopareigns** [comment]
Here's the way I squash commits on the browser version of github (no idea how to use other versions):

1. Make two branches, branch1 and branch2
2. Do all your changes on branch1
3. Make a pull request to merge branch1 into branch2
4. When merging, make sure to "squash and merge"

branch2 now has all of your changes using only one commit.

**Comment by prndev** [comment]
Well done. 👍

**Pull request closed without merging**
