### PR TITLE
Cherry-pick №2

### PR DESCRIPTION
**Pull request by Folant**
Restore some missing fixes

### CODE REVIEW

**Comment by Folant** [comment]
@goldifrocks 
From what I can see, changes from #189 is already on master, because it was cherry-picked in #194 (https://github.com/Free-Cities/Free-Cities/pull/194/commits/5167ee4362401dbba56916785274e41cd70cc8cf)

**Comment by goldifrocks** [comment]
ah, I got a bit confused over this cherry-pciking business, sorry about that!

**Comment by Folant** [comment]
I think it's complete now.

**Comment by freecitiesdev** [comment]
Is this necessary after #200? I'm seeing a lot of conflicts with the facility reports.

**Comment by Folant** [comment]
@freecitiesdev I will try resolve it now, since it contains some missing moments

**Comment by Folant** [comment]
Done.

**Pull request merged**
